### ISSUE TITLE
Performance regression in mtgp32 with uniform-double

### ISSUE THREAD

**Issue by AlexBrownAMD** [ROCmSoftwarePlatform/rocRAND#74] opened 2019-07-23 21:59 UTC
Merging pull request #71 (Vega20 changes) has caused a performance regression in one of the benchmarks. Performance drop happens for mtgp32 generator using uniform-double. 

**Benchmark before:**
mtgp32:
  uniform-double:
      Throughput =  555.562 GB/s, Samples =   69.445 GSample/s, AvgTime (1 trial) =    1.800 ms, Time (all) =   36.000 ms, Size = 134217728

**Benchmark after:**
mtgp32:
  uniform-double:
      Throughput =  397.233 GB/s, Samples =   49.654 GSample/s, AvgTime (1 trial) =    2.517 ms, Time (all) =   50.348 ms, Size = 134217728

**Comment by ex-rzr** [comment] 2019-07-24 03:02
https://github.com/ROCmSoftwarePlatform/rocRAND/pull/71/commits/0bed3dec3a6623e7a5c8e9b642cb8b81d7bbed68#diff-a1cfdd6bc5fe1da2d475b62d196499fdR244

MTGP32 uses 2 uints to generate 1 double value (uniform, normal and log-normal). There is no reason to use 1 uint, because double values are supposed to have much greater precision than floats.

So this commit changed MTGP32 so it works in the same way as Philox and XORWOW (while Mrg32k3a  and Sobol32 use 1 uint because Mrg32k3a generates a random number, not random bits and Sobol32 is a quasi-random generator).

**Comment by saadrahim** [comment] 2019-07-24 03:13
Does the performance test that exists be modified to drop the use of 1 uint if this is no longer required? Do we need to add a 2 uint based MTGP32 performance tests?

**Comment by ex-rzr** [comment] 2019-07-24 03:27
I'm not sure I understand your question, could you elablorate?

**Comment by saadrahim** [comment] 2019-07-24 03:53
I may have misunderstood.

A performance test showed regression for double types.
Your explanation is that the old behavior was not suitable for double type. It was corrected and performance dropped. But the randomness of the output increased as a result (not sure what the correct mathematical term is).

Thanks,
Saad

**Comment by ex-rzr** [comment] 2019-07-24 04:14
Yes, your conclusion is correct.

On the other hand, performance of MTGP32's normal and log-normal for both float and double is much better now. I think Alex can confirm this. There was no reason not to use a Box-Muller transform for MTGP32 too (instead of a slower inverse cumulative approach which is used only for Sobol32 now).

**Comment by AlexBrownAMD** [comment] 2019-07-24 14:24
Yep, performance improved for both normal and log-normal. uniform-double was the only one that dropped, but that makes sense, the library now generates better random doubles.

**Benchmark before:**
  normal-float:
      Throughput =  171.870 GB/s, Samples =   42.967 GSample/s, AvgTime (1 trial) =    2.909 ms, Time (all) =   58.184 ms, Size = 134217728
  normal-double:
      Throughput =  107.423 GB/s, Samples =   13.428 GSample/s, AvgTime (1 trial) =    9.309 ms, Time (all) =  186.180 ms, Size = 134217728
  log-normal-float:
      Throughput =  146.612 GB/s, Samples =   36.653 GSample/s, AvgTime (1 trial) =    3.410 ms, Time (all) =   68.207 ms, Size = 134217728
  log-normal-double:
      Throughput =   88.823 GB/s, Samples =   11.103 GSample/s, AvgTime (1 trial) =   11.258 ms, Time (all) =  225.167 ms, Size = 134217728

**Benchmark after:**
  normal-float:
      Throughput =  291.606 GB/s, Samples =   72.902 GSample/s, AvgTime (1 trial) =    1.715 ms, Time (all) =   34.293 ms, Size = 134217728
  normal-double:
      Throughput =  151.529 GB/s, Samples =   18.941 GSample/s, AvgTime (1 trial) =    6.599 ms, Time (all) =  131.988 ms, Size = 134217728
  log-normal-float:
      Throughput =  228.416 GB/s, Samples =   57.104 GSample/s, AvgTime (1 trial) =    2.189 ms, Time (all) =   43.780 ms, Size = 134217728
  log-normal-double:
      Throughput =  115.389 GB/s, Samples =   14.424 GSample/s, AvgTime (1 trial) =    8.666 ms, Time (all) =  173.327 ms, Size = 134217728

**Comment by saadrahim** [comment] 2019-08-13 16:16
Closing as issue was explained as expected behaviour.

**Closed by saadrahim** 2019-08-13 16:16 UTC
