### ISSUE TITLE
Call parameter type does not match function signature

### ISSUE THREAD

**Issue by Palmitoxico** [ROCmSoftwarePlatform/rocRAND#40] opened 2019-01-21 18:26 UTC
Hi,

I'm having problems when building the rocRAND library on my ArchLinux machine:

```
Call parameter type does not match function signature!
  %StackGuardSlot = alloca i8*, addrspace(5)
 i8**  call void @llvm.stackprotector(i8* %0, i8* addrspace(5)* %StackGuardSlot)
in function _Z14rocrand_kernelIN14rocrand_device14sobol32_engineILb0EEEEvPjS3_m
LLVM ERROR: Broken function found, compilation aborted!
Generating AMD GCN kernel failed in llc for target: gfx906
Call parameter type does not match function signature!
  %StackGuardSlot = alloca i8*, addrspace(5)
 i8**  call void @llvm.stackprotector(i8* %0, i8* addrspace(5)* %StackGuardSlot)
in function _Z14rocrand_kernelIN14rocrand_device14sobol32_engineILb0EEEEvPjS3_m
LLVM ERROR: Broken function found, compilation aborted!
Generating AMD GCN kernel failed in llc for target: gfx900
Call parameter type does not match function signature!
  %StackGuardSlot = alloca i8*, addrspace(5)
 i8**  call void @llvm.stackprotector(i8* %0, i8* addrspace(5)* %StackGuardSlot)
in function _Z14rocrand_kernelIN14rocrand_device14sobol32_engineILb0EEEEvPjS3_m
LLVM ERROR: Broken function found, compilation aborted!
Generating AMD GCN kernel failed in llc for target: gfx803
clang-8: error: linker command failed with exit code 7 (use -v to see invocation)
make[2]: *** [test/CMakeFiles/test_rocrand_kernel_sobol32.dir/build.make:91: test/test_rocrand_kernel_sobol32] Error 7
make[1]: *** [CMakeFiles/Makefile2:738: test/CMakeFiles/test_rocrand_kernel_sobol32.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Call parameter type does not match function signature!
  %StackGuardSlot = alloca i8*, addrspace(5)
 i8**  call void @llvm.stackprotector(i8* %0, i8* addrspace(5)* %StackGuardSlot)
in function _Z19rocrand_init_kernelIN14rocrand_device13xorwow_engineEEvPT_myy
LLVM ERROR: Broken function found, compilation aborted!
Generating AMD GCN kernel failed in llc for target: gfx906
Call parameter type does not match function signature!
  %StackGuardSlot = alloca i8*, addrspace(5)
 i8**  call void @llvm.stackprotector(i8* %0, i8* addrspace(5)* %StackGuardSlot)
in function _Z19rocrand_init_kernelIN14rocrand_device13xorwow_engineEEvPT_myy
LLVM ERROR: Broken function found, compilation aborted!
Generating AMD GCN kernel failed in llc for target: gfx900
Call parameter type does not match function signature!
  %StackGuardSlot = alloca i8*, addrspace(5)
 i8**  call void @llvm.stackprotector(i8* %0, i8* addrspace(5)* %StackGuardSlot)
in function _Z19rocrand_init_kernelIN14rocrand_device13xorwow_engineEEvPT_myy
LLVM ERROR: Broken function found, compilation aborted!
Generating AMD GCN kernel failed in llc for target: gfx803
```
I've built rocm, hcc and hip from scratch (master branch), but I keep getting the same error.

```
$ /opt/rocm/hcc/bin/hcc --version
HCC clang version 8.0.0 (https://github.com/RadeonOpenCompute/hcc-clang-upgrade.git 6ec3c61e09fbb60373eaf5a40021eb862363ba2c) (https://github.com/RadeonOpenCompute/llvm.git d5938b6c383ee68cf93d4508e48836d6118517e2) (based on HCC 1.3.18505-6cf476c2-6ec3c61e09-d5938b6c383 )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
```
```
$ /opt/rocm/hip/bin/hipcc --version
HIP version: 1.5.18494
HCC clang version 8.0.0 (https://github.com/RadeonOpenCompute/hcc-clang-upgrade.git 6ec3c61e09fbb60373eaf5a40021eb862363ba2c) (https://github.com/RadeonOpenCompute/llvm.git d5938b6c383ee68cf93d4508e48836d6118517e2) (based on HCC 1.3.18505-6cf476c2-6ec3c61e09-d5938b6c383 )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
```
Any hints?

Thanks,
Augusto.

**Comment by ex-rzr** [comment] 2019-01-22 14:39
Thank you for your report, I'll check this issue.

**Comment by ex-rzr** [comment] 2019-01-23 05:51
It works on hcc 1.3.18482 (the release deb from http://repo.radeon.com/rocm/apt/debian/).
It looks like this caused by recent changes in llvm or hcc.

Here is our config:
```
/opt/rocm/hip/bin/hipcc --version
HIP version: 1.5.18494
HCC clang version 8.0.0 (ssh://gerritgit/compute/ec/hcc-tot/clang 6ec3c61e09fbb60373eaf5a40021eb862363ba2c) (ssh://gerritgit/lightning/ec/llvm ab3b88ffc2ae50f55361a49aec89f6e95d9d0ec4) (based on HCC 1.3.18482-757fb49-6ec3c61-ab3b88f )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
```

https://github.com/RadeonOpenCompute/hcc/commits/roc-2.0.x
The difference is the last commit where llvm submodule updated.

@Palmitoxico, could you check 757fb492517b80e7c86338af5fc1a43d63cb25a9 commit?

**Comment by ex-rzr** [comment] 2019-01-23 05:52
@baerbock, could you also show your `/opt/rocm/hip/bin/hipcc --version` output?

**Comment by Palmitoxico** [comment] 2019-01-23 11:05
I've rebuilt ```hcc``` @ 757fb492517b80e7c86338af5fc1a43d63cb25a9 and ```hip```, same results.

```
$ /opt/rocm/hip/bin/hipcc --version
HIP version: 1.5.18494
HCC clang version 8.0.0 (https://github.com/RadeonOpenCompute/hcc-clang-upgrade.git 6ec3c61e09fbb60373eaf5a40021eb862363ba2c) (https://github.com/RadeonOpenCompute/llvm.git 6ae08f76c9c619f1aa3c7a16c29777aaeadbe1e1) (based on HCC 1.3.18482-757fb492-6ec3c61e09-6ae08f76c9c )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
```
As you can see, the only difference to your setup is the llvm version (which makes sense). Could you point me the commit which the llvm submodule was updated? It wasn't in 757fb492517b80e7c86338af5fc1a43d63cb25a9.

Thanks,
Augusto.

**Comment by ex-rzr** [comment] 2019-01-23 11:14
> I've rebuilt hcc @ 757fb492517b80e7c86338af5fc1a43d63cb25a9 and hip, same results.

What is llvm version in `/opt/rocm/hip/bin/hipcc --version` report now?

The top commit here: https://github.com/RadeonOpenCompute/hcc/commits/roc-2.0.x
https://github.com/RadeonOpenCompute/hcc/commit/6cf476c29792593f52cd66bd0bd96468b8dad7ea

May be "submodule compiler" stays as it was in 6cf476c when you checkout 757fb49? I don't have enough experience with git submodules, to be honest.

**Comment by Palmitoxico** [comment] 2019-01-23 11:41
The ```hipcc``` version showed above is built from 757fb492517b80e7c86338af5fc1a43d63cb25a9. It seems to be a problem with the git submodule checkout, I'll try clone and build everything from scratch and report my results on 757fb49251.

**Comment by Palmitoxico** [comment] 2019-01-23 12:49
Nope, 757fb492517b80e7c86338af5fc1a43d63cb25a9 still throwing the same error when building rocrand.
```
$ /opt/rocm/hip/bin/hipcc --version
HIP version: 1.5.18494
HCC clang version 8.0.0 (https://github.com/RadeonOpenCompute/hcc-clang-upgrade.git 6ec3c61e09fbb60373eaf5a40021eb862363ba2c) (https://github.com/RadeonOpenCompute/llvm.git 6ae08f76c9c619f1aa3c7a16c29777aaeadbe1e1) (based on HCC 1.3.18482-757fb492-6ec3c61e09-6ae08f76c9c )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
```

This matches with the submodules versions:
```
$ git show 757fb492517b80e7c86338af5fc1a43d63cb25a9
commit 757fb492517b80e7c86338af5fc1a43d63cb25a9 (HEAD -> makepkg)
Author: Siu Chi Chan <siuchi.chan@amd.com>
Date:   Tue Dec 4 12:36:08 2018 -0500

    [Config]update submodule links for ROCm 2.0
    
    Change-Id: I6f173732f39a7b77abc46be62b71ae5532a970b1

diff --git a/clang b/clang
index f42c0a13..6ec3c61e 160000
--- a/clang
+++ b/clang
@@ -1 +1 @@
-Subproject commit f42c0a1364ef557764a5dcdd0ec395950bbb6ab6
+Subproject commit 6ec3c61e09fbb60373eaf5a40021eb862363ba2c
diff --git a/compiler b/compiler
index b45e9ad5..6ae08f76 160000
--- a/compiler
+++ b/compiler
@@ -1 +1 @@
-Subproject commit b45e9ad50ee222c12e5806e1feedf07020fa1001
+Subproject commit 6ae08f76c9c619f1aa3c7a16c29777aaeadbe1e1
diff --git a/compiler-rt b/compiler-rt
index 324a5948..638adb5b 160000
--- a/compiler-rt
+++ b/compiler-rt
@@ -1 +1 @@
-Subproject commit 324a59489df63e49e2303495ea0c0c156b3eeec3
+Subproject commit 638adb5bd55f84981257ee0a634cd414a9374021
diff --git a/rocdl b/rocdl
index 48d92837..a0c24d5c 160000
--- a/rocdl
+++ b/rocdl
@@ -1 +1 @@
-Subproject commit 48d92837bdf7db005d182d05ef51fe8422263e02
+Subproject commit a0c24d5cd627a6cd727774d1c6880e940ae9943e
```

**Comment by ex-rzr** [comment] 2019-01-23 13:11
Weird, we still have different llvm versions (ab3b88ffc2ae50f55361a49aec89f6e95d9d0ec4 vs 6ec3c61e09fbb60373eaf5a40021eb862363ba2c).

**Comment by ex-rzr** [comment] 2019-01-23 13:18
ab3b88ffc2ae50f55361a49aec89f6e95d9d0ec4 does not exist in https://github.com/RadeonOpenCompute/llvm and https://github.com/llvm-mirror/llvm

**Comment by VincentSC** [comment] 2019-01-30 21:58
I think this gets out of scope and I'm closing this issue.

This is more a compiler-problem in the latest HIP+LLVM than an problem with rocRAND. We strongly recommend to use rocRAND and rocPRIM in the continuous integration of new versions of HIP, but we cannot support compiler-issues that do not clearly relate to . 

For solving the issue, try to go step-by-step as you now try to hit it with the latest bleeding edge. So check out a version of HIP/HCC + LLVM that equals ROCm 2.0 that is known to work (the version ex-rzr mentions). This way you can identify what exact change causes the problem.

If you find that rocRAND uses API-calls from HIP/HCC that have been deprecated, please open a new issue specifically for that.

**Closed by VincentSC** 2019-01-30 21:58 UTC

**Comment by baerbock** [comment] 2019-02-01 18:43
@VincentSC I have been using HCC from ROCm 2.0 when my first rocRAND build originally failed. So please reopen this!

**Comment by VincentSC** [comment] 2019-02-16 16:00
Sorry for this. We need something to reproduce *and* official+supported libraries are used. If you install the default ROCm 2.1 and explain how to reproduce, then I'll reopen. Now the support got full on LLVM-debunking.
